# Generated by Django 5.2.8 on 2025-11-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='two_factor_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
