# Generated by Django 5.2.8 on 2025-11-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_two_factor_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('2fa', 'Two Factor Authentication'), ('password_reset', 'Password Reset')], default='2fa', max_length=20),
        ),
    ]
