# Generated by Django 5.2.8 on 2025-11-20 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_expense_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-created_at']},
        ),
    ]
