# Generated by Django 5.2.8 on 2025-11-21 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_alter_expense_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='verification_status',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
